### ISSUE TITLE
Issues with gulp

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox-microsite#76]
I've followed https://demisx.github.io/gulp4/2015/01/15/install-gulp4.html and see

```sh
$ gulp -v
[17:28:15] CLI version 1.3.0
[17:28:15] Local version 4.0.0-alpha.2
```

When I run `gulp build`, I get:

```sh
$ gulp build
module.js:487
    throw err;
    ^

Error: Cannot find module 'yargs'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jeffy/git/workbox-microsite/node_modules/gulp/node_modules/gulp-cli/index.js:7:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

I think `yargs` is just being used internally by `gulp`, so I'm not sure why the dependency isn't getting picked up. I'll investigate further, but wanted to get the details down in case anyone else has ideas.

**Comment by jeffposnick** [comment]
Sigh... as with many things `npm`, `rm- rf node_modules package-lock.json && npm install` seems to have cleared it up.
